services:
  api:
    image: node:20-alpine
    container_name: whatsapp-bot
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
